name: Exort
version: "${version}"
main: com.zxcmc.exort.core.ExortPlugin
description: "${description}"
api-version: "1.21.7"
authors: ["phantomfighterxx"]
libraries:
  - org.xerial:sqlite-jdbc:3.45.3.0
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: false
      join-classpath: true
    ProtectionStones:
      load: BEFORE
      required: false
      join-classpath: false
    GriefPrevention:
      load: BEFORE
      required: false
      join-classpath: true
    Towny:
      load: BEFORE
      required: false
      join-classpath: true
    Lands:
      load: BEFORE
      required: false
      join-classpath: true
    Residence:
      load: BEFORE
      required: false
      join-classpath: true
    WorldEdit:
      load: BEFORE
      required: false
      join-classpath: true
    FastAsyncWorldEdit:
      load: BEFORE
      required: false
      join-classpath: true
    packetevents:
      load: BEFORE
      required: false
      join-classpath: true
    Nexo:
      load: AFTER
      required: false
      join-classpath: false
    ItemsAdder:
      load: AFTER
      required: false
      join-classpath: false
    Chorusfix:
      load: AFTER
      required: false
      join-classpath: false
permissions:
  exort.storagenetwork.admin:
    description: Allows use of Exort administrative commands.
    default: op
    children:
      exort.storagenetwork.give: true
  exort.storagenetwork.give:
    description: Allows opening the Exort item inventory and using /exort give.
    default: "false"
